#spring:
#mesgkeyFromApp: Message from Application 2
#name: client1
#server:
# port: ${PORT:8090}
management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  application:
    name: quark12